### ISSUE TITLE
[BUG] obj_screen is not an array

### ISSUE THREAD

**Issue by gabosonicy** [MrAwesomeLuigi/undertalemods#14]
(Please include the mod you are reporting in the Labels section)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information:**
 - Mod Version: [e.g. v1.0]

**Additional context**

**Comment by gabosonicy** [comment]
so i got this weird error
![image](https://github.com/user-attachments/assets/358de534-7904-4f4c-ac19-88ace4c793f8)
does anybody know what to do?

**Comment by MrAwesomeLuigi** [comment]
youre not using the undertale.exe thats in the zip folder
