### ISSUE TITLE
[BUG] Music not loading when playing Deltarune: Plus

### ISSUE THREAD

**Issue by Al-AmeenAdewunmi** [MrAwesomeLuigi/undertalemods#17]
The music doesn't seem to load when booting up the mod. Sound effects work, though. What's odd about this is that it only happens when I'm loading up the mod through the mod manager. The music works just fine when loading it through Steam or even a standalone copy.

Mod: https://gamejolt.com/games/deltaruneplus/738029

**Comment by MrAwesomeLuigi** [comment]
fixed in v2.1.0
