### ISSUE TITLE
.xdelta files are not being patched on undertale but they are on deltarune

### ISSUE THREAD

**Issue by sandvich67** [MrAwesomeLuigi/undertalemods#2]
**Describe the bug**
read the title

**To Reproduce**
I don't know why it is happening

**Expected behavior**
patch the .xdelta file to a data.win file

**Screenshots**
I can't give any Screenshots of it

**Information:**
version 1.0

**Additional context**

**Comment by MrAwesomeLuigi** [comment]
make sure you are on the undertale mod list when you press import
if that doesnt work could you send one of the .xdeltas you are trying to patch?

**Comment by sandvich67** [comment]
> make sure you are on the undertale mod list when you press import if that doesnt work could you send one of the .xdeltas you are trying to patch?

I am going to try using delta patcher on a normal data.win and importing that instead

**Comment by MrAwesomeLuigi** [comment]
deltapatcher or importing the mod?

**Comment by sandvich67** [comment]
> deltapatcher or importing the mod?

importing the mod it just put a normal data.win again

**Comment by sandvich67** [comment]
> > deltapatcher or importing the mod?
> 
> importing the mod it just put a normal data.win again

im going to try putting the data.win that gets put into the mod folder into the game files on steam

**Comment by sandvich67** [comment]
> > > deltapatcher or importing the mod?
> > 
> > 
> > importing the mod it just put a normal data.win again
> 
> im going to try putting the data.win that gets put into the mod folder into the game files on steam

so it turns out I was wrong about the issue the real issue is that it just isn't putting the data.win into the game's files

**Comment by MrAwesomeLuigi** [comment]
oh bruh
after importing the mod, select it in the mod list
itll show up on the right menu, and then press play

**Comment by sandvich67** [comment]
> oh bruh after importing the mod, select it in the mod list itll show up on the right menu, and then press play

I'm already doing that

**Comment by MrAwesomeLuigi** [comment]
you shouldn't need to mess with the steam files or mod folder. importing the data.win and pressing play on the mod should start the mod up
could you send the .xdelta you are trying to use?

**Comment by sandvich67** [comment]
> you shouldn't need to mess with the steam files or mod folder. importing the data.win and pressing play on the mod should start the mod up could you send the .xdelta you are trying to use?

I fixed it

**Comment by sandvich67** [comment]
> > you shouldn't need to mess with the steam files or mod folder. importing the data.win and pressing play on the mod should start the mod up could you send the .xdelta you are trying to use?
> 
> I fixed it

by re installing the mod manager
