### ISSUE TITLE
getting teleported to random rooms

### ISSUE THREAD

**Issue by sandvich67** [MrAwesomeLuigi/undertalemods#5]
**Describe the bug**
when loading a save in undertale it loads me into a random room from the end game

**To Reproduce**
save, quit and load the save

**Expected behavior**
loading to the room you saved in

**Screenshots**

![Screenshot 2024-06-01 193637](https://github.com/MrAwesomeLuigi/undertalemods/assets/170859232/f71923db-bba4-4647-aabf-401d32fcafc9)
![Screenshot 2024-06-01 193654](https://github.com/MrAwesomeLuigi/undertalemods/assets/170859232/312550c3-615a-4a4d-88ac-12ba83cf090b)

**Information:**
 1.0

**Additional context**
mod manager

**Comment by MrAwesomeLuigi** [comment]
mod manager currently cannot change anything with save files. this is either due to the mod you are playing or you have just edited the save file
