### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by JoshuaHar** [MrAwesomeLuigi/undertalemods#6]
**Describe the bug**
It just crashes as soon as it loads up.

**To Reproduce**
Load up the game.

**Expected behavior**
It to work.

**Screenshots**
![image_2024-06-02_154658342](https://github.com/MrAwesomeLuigi/undertalemods/assets/156957730/a0628b6d-553b-4fd3-bc4d-78bd3a10873d)

**Information:**
 - Mod Version: v3.0.1

**Additional context**
N/A

**Comment by MrAwesomeLuigi** [comment]
You need to use the 'UNDERTALE.exe' that came with the mod download
