### ISSUE TITLE
[BUG] Chaos Mod Unable To Launch

### ISSUE THREAD

**Issue by Underballs** [MrAwesomeLuigi/undertalemods#8]
(Please include the mod you are reporting in the Labels section)

**Describe the bug**
Whenever I attempt to open the Chaos Mod for Undertale, the game crashes, giving me a FATAL ERROR for "trying to index a variable which is not an array
at gml_Script_scr_murderlv"

**To Reproduce**
Step 1: Open the modded game.
**Expected behavior**
I expected the game to boot up normally
**Screenshots**
![image](https://github.com/user-attachments/assets/dc327eba-2d22-43b6-96f6-9178a2bbad63)

**Information:**
 - Mod Version: [e.g. v1.0]

**Additional context**

**Comment by Underballs** [comment]
OK, I'll try that instead. Thank you for the help.

**Comment by Underballs** [comment]
Whenever I try to open the included UNDERTALE.exe file, it sends me to the File Explorer. If I try to open the included UNDERTALE.exe, it doesn't open. When I try the UNDERTALE.exe file from Steam, it opens but then closes. When I try the data.win file from Steam, it has the same crashing issue as before.

**Comment by MrAwesomeLuigi** [comment]
if the included exe file opens file explorer, you need to select the patched data.win.

**Comment by Underballs** [comment]
Already did the patched data.win from Steam, closes as well.

**Comment by MrAwesomeLuigi** [comment]
you could try installing the mod with my [mod manager](https://gamebanana.com/tools/16960), do the installation in the readme and import the .zip file and it should install the mod

**Comment by Underballs** [comment]
Will try tomorrow, thanks for all of the help.
