### ISSUE TITLE
[BUG] it keeps closing

### ISSUE THREAD

**Issue by Lilman12513** [MrAwesomeLuigi/undertalemods#9]
(mod manager)

**Describe the bug**
after running the undertale chaos mod, I tried to pick a different mod and it would not stop closing I used start.bat it ran the command, it showed a back screen on the mod for half a second, then closed instantly, and then I ran the main.pyw, it shows a back screen on the mod for half a second, then closed instantly. please help

**To Reproduce**
Steps to reproduce the behavior: nothing, nothing works, i tried re-downloading the mod manager, doesn't work.

**Expected behavior**
A clear and concise description of what you expected to happen.: I expected to open the mod manager, load in the mods, and let me play a different mod. 

**Screenshots**
If applicable, add screenshots to help explain your problem. can't

**Information:**
 - Mod Version: v1.0.0

**Additional context**

**Comment by MrAwesomeLuigi** [comment]
please rename 'main.pyw' to 'main.py' and run it directly
are there any errors that show up?

**Comment by MrAwesomeLuigi** [comment]
did you run 'startup.bat'?

**Comment by Lilman12513** [comment]
> did you run 'startup.bat'?

yes
twice

**Comment by Lilman12513** [comment]
and before it stopped working it was working,

**Comment by MrAwesomeLuigi** [comment]
can you send me a picture of the 'files' folder and the 'Mods/Undertale' folder? I'm not sure what exactly is going wrong here.

**Comment by Lilman12513** [comment]
![Screenshot 2024-07-27 013150](https://github.com/user-attachments/assets/8e3ffaef-8b55-4bf2-8ec8-c82952fdaff3)
![Screenshot 2024-07-27 013234](https://github.com/user-attachments/assets/112d1143-0700-4b0b-9070-5daf38e64a80)


> can you send me a picture of the 'files' folder and the 'Mods/Undertale' folder? I'm not sure what exactly is going wrong here.

**Comment by Lilman12513** [comment]
> can you send me a picture of the 'files' folder and the 'Mods/Undertale' folder? I'm not sure what exactly is going wrong here.

IVE FOUND THE ISSUE! its because the NONE value in main.pyw just set all 8bitoperatorjveregular in the font check to be fnt.main

**Comment by Lilman12513** [comment]
it worked for me
